- hosts: all
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: Please choose the target host IP {{play_hosts}}
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: target_host

- hosts: target_host
  tasks:
  - debug: 
      msg="Chosen target {{play_hosts}}"