- hosts: target_host
  gather_facts: no
  become: true
  tasks:
    - name: Install Python3 on Debian or Ubuntu systems
      apt:
        name: "python3"
        state: latest
      when:
      - ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"
    - name: Install Python3 on CentOS or RHEL systems
      yum:
        name: "python3"
        state: latest
      when:
      - ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat"
