- hosts: target_host
  gather_facts: no
  become: true
  tasks:
    - name: Install Python3 and Python3-apt on Debian or Ubuntu systems
      apt:
        name: "python3-pip"
        state: latest
      when:
      - ansible_facts['os_family'] == "Debian"
    - name: Install Python3 and Python3-apt on CentOS or RHEL systems
      yum:
        name: "python3-pip"
        state: latest
      when:
      - ansible_facts['os_family'] == "RedHat"
