# Choose target_host
- hosts: localhost
  gather_facts: false
  vars:
    deluge_target: "{{ target | default('') }}"
  tasks:
    - name: Add user from extra_vars
      add_host:
        name: "{{ target }}"
        groups: target_host
      when:
        - "deluge_target | length > 0"

    - name: Get 'target_host' from user input.
      include_tasks: ./tasks/choose_target.yml
      when:
        - "'target_host' not in groups['all']"
        - "'target_host' not in groups"

- hosts: target_host
  gather_facts: false
  become: true
  vars:
    deluge_user: "{{ user | default('') }}"
    deluge_action: "{{ action | default('') }}"
  tasks:
    - name: Print HOSTNAME and IP ADDRESS.
      debug:
        msg:
          - "Chosen target:"
          - "{{ inventory_hostname }}"
          - "{{ ansible_ssh_host }}"

    - name: Ask for User that has Deluge.
      pause:
        prompt: Please choose the user that has Deluge
      register: user_input
      when:
        - "deluge_user | length == 0"

    - name: Save user input as user that has Deluge.
      set_fact:
        user: "{{ user_input.user_input }}"
      when:
        - "deluge_user | length == 0"

    - name: Ask the action to be made.
      pause:
        prompt: What do you want to do? [stop, start, start_web, restart, restart_web]
      register: action_input
      when:
        - "deluge_action | length == 0"

    - name: Save user input as action to be made.
      set_fact:
        deluge_action: "{{ action_input.user_input }}"
      when:
        - "deluge_action | length == 0"

    - name: Stop the Deluge related services.
      block:
        - name: Check if deluged is running. [1/4]
          shell: 'ps -eaf | grep deluged | grep -cv grep'
          register: process
          failed_when: ( process.rc not in [ 0, 1 ] )
        - name: Stop deluged process. [2/4]
          include_tasks: ./tasks/pkill.yml
          with_items: "deluged"
          when: process.stdout == "1"
        - name: Check if deluge web is running. [3/4]
          shell: 'ps -eaf | grep deluge-web | grep -cv grep'
          register: process
          failed_when: ( process.rc not in [ 0, 1 ] )
        - name: Stop the Deluge WebUI. [4/4]
          include_tasks: ./tasks/pkill.yml
          with_items: "deluge-web"
          when: process.stdout == "1"
      become: yes
      become_user: "{{ deluge_user }}"
      when: deluge_action == "stop"
    
    - name: Start deluge service only.
      block:
        - name: Start deluged process. [1/2]
          shell: deluged
        - name: Allow remote access. [2/2]
          shell: deluge-console "config -s allow_remote True"
      become: yes
      become_user: "{{ deluge_user }}"
      when: deluge_action == "start"

    - name: Start deluge with WebUI access only.
      block:
        - name: Start deluged process. [1/2]
          shell: deluged
        - name: Start deluge web UI. [2/2]
          shell: deluge-web --fork
      become: yes
      become_user: "{{ deluge_user }}"
      when: deluge_action == "start_web"

    - name: Restart deluge service only.
      block:
        - name: Stop deluged process. [1/3]
          include_tasks: ./tasks/pkill.yml
          with_items: "deluged"
        - name: Start deluged process. [2/3]
          shell: deluged
        - name: Allow remote access. [3/3]
          shell: deluge-console "config -s allow_remote True"
      become: yes
      become_user: "{{ deluge_user }}"
      when: deluge_action == "restart"

    - name: Restart deluge with WebUI access only.
      block:
        - name: Stop deluged process. [1/4]
          include_tasks: ./tasks/pkill.yml
          with_items: "deluged"
        - name: Stop deluged process. [2/4]
          include_tasks: ./tasks/pkill.yml
          with_items: "deluge-web"
        - name: Start deluged process. [3/4]
          shell: deluged
        - name: Start deluge web UI. [4/4]
          shell: deluge-web --fork
      become: yes
      become_user: "{{ deluge_user }}"
      when: deluge_action == "restart_web"