- hosts: target_host
  gather_facts: no
  become: true
  tasks:
  - name: Update repository cache on Debian or Ubuntu systems
    apt:
      update_cache: true
    when:
    - ansible_facts['os_family'] == "Debian"
  - name: Update repository cache on CentOS or RHEL systems
    yum:
      update_cache: true
    when:
    - ansible_facts['os_family'] == "RedHat"