- hosts: target_host
  gather_facts: no
  become: true
  tasks:
  - name: Upgrade all current packages on Debian or Ubuntu systems
    apt:
      upgrade: dist
    when:
    - ansible_facts['os_family'] == "Debian"
  - name: Upgrade all current packages on CentOS or RHEL systems
    yum:
      name: "*"
      state: latest
    when:
    - ansible_facts['os_family'] == "RedHat"