- hosts: target_host
  gather_facts: no
  become: true
  tasks:
  - name: Update repository cache on Debian or Ubuntu systems
    apt:
      update_cache: true
    when:
    - ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"
  - name: Upgrade all current packages on Debian or Ubuntu systems
    apt:
      upgrade: dist
    when:
    - ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"
  - name: Update repository cache on CentOS or RHEL systems
    yum:
      update_cache: true
    when:
    - ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat"
  - name: Upgrade all current packages on CentOS or RHEL systems
    yum:
      name: "*"
      state: latest
    when:
    - ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat"
