- hosts: target_host
  gather_facts: no
  become: true
  tasks:
    - name: Install Python3 and Python3-apt on Debian or Ubuntu systems
      apt:
        name: "python3-apt"
        state: latest
      when:
      - ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"
    - name: Install Python3 and Python3-apt on CentOS or RHEL systems
      yum:
        name: "{{ item }}"
        state: latest
      loop:
      - python3
      - python3-apt
      when:
      - ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat"
    - name: Upgrade all current packages on CentOS or RHEL systems
      yum:
        name: "*"
        state: latest
      when:
      - ansible_facts['os_family'] == "RedHat"

- hosts: target_host
  tasks:
    - name: Create directory
      file:
      path: ~/test
      state: directory